{
 "title": "ICOS App View",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "icos_telemetry_db", "label": "ICOS Telemetry DB", "query": "prometheus" },
   {
    "name": "app_name",
    "label": "App",
    "query": {
     "query": "label_values(tlum_workload_info,icos_app_name)"
    }
   },
   {
    "name": "app_instance",
    "label": "Instance",
    "query": {
     "query": "label_values(tlum_workload_info{icos_app_name=\"$app_name\"},icos_app_instance)"
    }
   },
   {
    "name": "app_component",
    "label": "Component",
    "query": {
     "query": "label_values(tlum_workload_info{icos_app_name=\"$app_name\"},icos_app_component)"
    }
   },
   {
    "name": "app_task",
    "label": "Task",
    "query": {
     "query": "label_values(compss_avgTime_ratio{icos_app_name=\"$app_name\"},CoreSignature)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{icos_app_instance=\"$app_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage on nodes where the application is running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "tlum_workload_info{icos_app_instance=\"$app_instance\"} *on(icos_host_id) group_left avg without (cpu) (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[2m]))",
     "legendFormat": "\"{{icos_app_component}}\" running on \"{{icos_host_name}}\""
    }
   ]
  },
  {
   "title": "App CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{icos_app_instance=\"$app_instance\"}",
     "legendFormat": "{{icos_app_component}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{icos_app_instance=\"$app_instance\"}",
     "legendFormat": "{{icos_app_component}}"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_filesystem_usage_bytes{icos_app_instance=\"$app_instance\"}",
     "legendFormat": "{{icos_app_component}}"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "label_replace(tlum_workload_info{icos_app_instance=\"$app_instance\"}, \"kubernetes_pod_name\", \"$1\", \"name\", \"(.+)\") *on(kubernetes_pod_name) group_left sum by (kubernetes_pod_name) (scaph_process_power_consumption_microwatts) / 1000",
     "legendFormat": "{{icos_app_component}}"
    }
   ]
  },
  {
   "title": "Policy Enforced",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "plm_policy_enforced{icos_app_name=\"$app_name\", icos_app_instance=\"$app_instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "COMPSs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "ETA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(compss_avgTime_ratio{CoreSignature=\"$app_task\", icos_app_name=\"$app_name\", icos_app_instance=\"$app_instance\", icos_app_component=\"$app_component\"} * compss_pendTasks_ratio{CoreSignature=\"$app_task\", icos_app_name=\"$app_name\", icos_app_instance=\"$app_instance\", icos_app_component=\"$app_component\"}) / sum(compss_node_info{property=\"computing_units\", icos_app_name=\"$app_name\", icos_app_instance=\"$app_instance\", icos_app_component=\"$app_component\"}) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pending Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "compss_pendTasks_ratio{CoreSignature=\"$app_task\", icos_app_name=\"$app_name\", icos_app_instance=\"$app_instance\", icos_app_component=\"$app_component\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average task duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "compss_avgTime_ratio{CoreSignature=\"$app_task\", icos_app_name=\"$app_name\", icos_app_instance=\"$app_instance\", icos_app_component=\"$app_component\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}