{
 "title": "Log Visualization",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "icos_logs_db", "query": "grafana-opensearch-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Anomaly score (mean)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "decimalSeparator": ".",
     "delimiter": ",",
     "metrics": [
      { "field": "anomaly_score", "id": "1", "type": "avg" }
     ],
     "schema": [
      { "name": "", "type": "string" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Anomaly score per 10m (mean)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "decimalSeparator": ".",
     "delimiter": ",",
     "metrics": [
      { "field": "anomaly_score", "id": "1", "type": "avg" }
     ],
     "schema": [
      { "name": "", "type": "string" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Anomaly score per 10s (mean)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "decimalSeparator": ".",
     "delimiter": ",",
     "metrics": [
      { "field": "anomaly_score", "id": "1", "type": "avg" }
     ],
     "schema": [
      { "name": "", "type": "string" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Anomaly score (max)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "decimalSeparator": ".",
     "delimiter": ",",
     "metrics": [
      { "field": "anomaly_score", "id": "1", "type": "max" }
     ],
     "schema": [
      { "name": "", "type": "string" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Count (Anomaly_score > 0.7)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "decimalSeparator": ".",
     "delimiter": ",",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "anomaly_score:[0.7 TO 1]",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Count per day (Anomaly_score > 0.7)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "decimalSeparator": ".",
     "delimiter": ",",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "anomaly_score:[0.7 TO 1]",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Max Anomaly score > 0.7",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "decimalSeparator": ".",
     "delimiter": ",",
     "metrics": [
      {
       "field": "anomaly_score",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "schema": [
      { "name": "", "type": "string" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Count Unknown logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "decimalSeparator": ".",
     "delimiter": ",",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "template_id:0 OR unknown:true",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Logs count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "decimalSeparator": ".",
     "delimiter": ",",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "schema": [
      { "name": "", "type": "string" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "schema": [
      { "name": "", "type": "string" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}