{
 "title": "ICOS Agent View-UC4",
 "time": { "from": "2024-03-25T09:10:47.239Z", "to": "2024-03-25T10:35:32.123Z" },
 "templating": {
  "list": [
   { "name": "icos_telemetry_db", "label": "ICOS Telemetry DB", "query": "prometheus" },
   {
    "name": "agent_id",
    "label": "ICOS Agent Id",
    "query": {
     "query": "label_values(tlum_host_info,icos_agent_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "k8s_node_cpu_utilization_ratio{icos_agent_id=\"$agent_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device Location",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "tlum_host_info{icos_agent_id=\"$agent_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ICOS Hosts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "tlum_host_info{icos_agent_id=\"$agent_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Security (SCA Score)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tlum_host_info{icos_agent_id=\"$agent_id\"} * on(hostname) group_right(id, icos_host_name) label_replace(label_replace(SCA_score, \"ip\", \"$1\", \"agent_ip\", \"(.+)\"), \"hostname\", \"$1\", \"agent_hostname\", \"(.+)\")",
     "legendFormat": "{{icos_host_name}}"
    }
   ]
  },
  {
   "title": "Security (Vulnerabilities)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tlum_host_info{icos_agent_id=\"$agent_id\"} * on(hostname) group_right(id, icos_host_name) label_replace(label_replace(vulnerabilities, \"ip\", \"$1\", \"agent_ip\", \"(.+)\"), \"hostname\", \"$1\", \"agent_hostname\", \"(.+)\")",
     "legendFormat": "{{icos_host_name}} {{severity}}"
    }
   ]
  }
 ]
}